#!/bin/bash
#docker-compose rm -f

set -euo pipefail
if [ -f build.env ];then
  export $(grep -v '^#' build.env | xargs)
fi
docker compose stop
docker compose rm -f

#This is useful for debugging
#docker compose up --build --progress=plain 2>&1 | tee DockerComposeBuild.log

DOCKER_BUILDKIT=1 \
BUILDKIT_PROGRESS=plain \
docker compose build \
  2>&1 | tee "Docker.log"
#  --no-cache \
docker compose up 2>&1 | tee "Docker.log"
