#!/bin/bash
#docker-compose rm -f
export BUILDKIT_PROGRESS=plain

set -euo pipefail
if [ -f build.env ];then
  export $(grep -v '^#' build.env | xargs)
fi
docker compose stop
docker compose rm -f
docker compose up --build 2>&1 | tee DockerComposeBuild.log

#This is useful for debugging
#docker compose up build --no-cache --progress=plain 2>&1 | tee DockerComposeBuild.log
docker compose up

