version: "3.9"

services:
  django:
    build:
      context: .
      dockerfile: AtlasContainer/Dockerfile
      args:
        DevMode: ${DevMode:-False}
        CustomCA: ${CustomCA:-False}
        UserId: ${UserId:-1000}
        GroupId: ${GroupId:-1000}
        AppUserName: ${AppUserName:-Atlas}
        PythonRoot: ${PythonRoot:-/python}
        PythonVersion: ${PythonVersion:-3.14.1}
        AptProxy: ${AptProxy:-False}
    env_file: secrets.env
    depends_on:
      - db
    volumes:
      - ./AtlasFiles:/AtlasFiles
      - AtlasStatic:/AtlasFiles/Atlas/static
      - AtlasMedia:/AtlasFiles/Atlas/media
    ports:
      - "8000:8000"
  db:
    build:
      context: ./PostgresBuild
      args:
        UserId: ${UserId:-1000}
        GroupId: ${GroupId:-1000}
        AppUserName: ${AppUserName:-Atlas}
    env_file: secrets.env
    volumes:
      - DBData2:/var/lib/postgresql/data
    expose:
      - "5432"
  caddy:
    image: caddy:latest
    # build:
      # context: .
      # dockerfile: CaddyBuild/Dockerfile
      # args:
        # CustomCA: ${CustomCA:-False}
    container_name: atlas-caddy
    env_file: secrets.env
    environment:
      AtlasServer: django
    depends_on:
      - django
    ports:
      - "443:443"
      - "8080:8080"
    volumes:
      - ./CaddyConfig/${CaddyFileVersion-CaddyFileDev}:/etc/caddy/Caddyfile
      - AtlasStatic:/AtlasStatic
      - AtlasMedia:/AtlasMedia
volumes:
  AtlasStatic:
  AtlasMedia:
  DBData2:
